### ISSUE TITLE
画像アップロード、管理者権限、パスワード確認欄、ページングを追加する

### ISSUE THREAD

**Issue by kazweda** [kazweda/laravel-crud#10]
https://zenn.dev/nenenemo/articles/c7485cc41153dc

**Comment by kazweda** [comment]
## マイグレーション作成
```
sail artisan make:migration add_columns_to_users_table --table=users
```

**Comment by kazweda** [comment]
phpmyadmin起動時の警告
```
sail phpmyadmin The requested image's platform (linux/amd64) does not match the detected host platform
```
に対して
docker-compose.yml
```yml
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        platform: linux/amd64
        links:
            - mysql:mysql
        ports:
            - 8080:80
        environment:
            # PMA_USER: "${DB_USERNAME}"
            # PMA_PASSWORD: "${DB_PASSWORD}"
            PMA_HOST: mysql
        networks:
            - sail
```
platformを記述する。
